import Link from "next/link";
import { ArrowRight, CalendarDays, Check, Heart, MapPin, Music2, Sparkles } from "lucide-react";
const templates = [{ name: "The Garden", style: "ELEGANT · BOTANICAL", tone: "sage", initials: "A & S", date: "SABTU, 24 OKTOBER 2026" }, { name: "A Love Story", style: "ROMANTIC · CLASSIC", tone: "rose", initials: "R & N", date: "MINGGU, 08 NOVEMBER 2026" }, { name: "The Beginning", style: "MODERN · MINIMAL", tone: "sand", initials: "D & K", date: "JUMAT, 20 NOVEMBER 2026" }];
const features = ["RSVP & konfirmasi kehadiran", "Galeri dan kisah perjalanan", "Peta lokasi acara", "Musik untuk menemani cerita", "Daftar tamu dalam satu tempat", "Statistik kunjungan undangan"];
export default function Home() {
  return <main>
    <header className="site-header"><Link href="/" className="brand"><span className="brand-mark">r.</span><span>ruang<span className="brand-light">janji</span></span></Link><nav className="hidden items-center gap-8 text-sm text-stone-600 md:flex"><a href="#template">Template</a><a href="#cara-kerja">Cara kerja</a><a href="#fitur">Fitur</a><a href="#harga">Harga</a></nav><div className="flex items-center gap-3"><Link href="/login" className="hidden px-3 py-2 text-sm font-medium text-stone-700 sm:block">Masuk</Link><Link href="/register" className="button-primary !px-4 !py-2.5">Buat undangan <ArrowRight size={15} /></Link></div></header>
    <section className="hero-shell"><div className="hero-copy"><div className="eyebrow"><Sparkles size={14} /> HARI ISTIMEWA, CERITA SELAMANYA</div><h1>Awal cerita indah,<br /><em>dibagikan dengan cinta.</em></h1><p className="hero-description">Undangan digital yang terasa personal. Rancang hari istimewamu, bagikan ceritanya, dan sambut setiap orang yang kamu sayangi.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/register" className="button-primary">Mulai buat undangan <ArrowRight size={16} /></Link><a href="#template" className="button-secondary">Jelajahi desain</a></div><div className="hero-proof"><div className="proof-avatars"><span>A</span><span>S</span><span>R</span><span>+</span></div><span>Dibuat dengan sepenuh hati, untuk hari terindahmu</span></div></div><div className="hero-art"><div className="hero-glow"/><div className="invitation-card"><div className="card-topline">WEDDING INVITATION <span>✳</span> 24.10.26</div><div className="card-flower">❧</div><div className="card-kicker">THE WEDDING OF</div><div className="card-names">Aditya <i>&</i><br />Saraswati</div><div className="card-rule"/><div className="card-date">SABTU, 24 OKTOBER 2026</div><div className="card-place"><MapPin size={12}/> Ubud, Bali</div><div className="card-bottom">DENGAN CINTA, KAMI MENGUNDANG</div></div><div className="float-note"><Heart size={14} fill="currentColor"/> hari yang kami nantikan</div><div className="float-stamp">SAVE<br/>THE<br/><b>DATE</b></div></div></section>
    <section className="trust-strip"><span>SEBUAH CERITA, DALAM SETIAP DETAIL</span><div><span>✳</span> Dirancang personal</div><div><span>✳</span> Mudah dibagikan</div><div><span>✳</span> Selalu dikenang</div></section>
    <section id="template" className="section-wrap"><div className="section-heading"><div><div className="eyebrow">PILIH YANG PALING KAMU</div><h2>Setiap kisah punya <em>caranya sendiri.</em></h2></div><a className="text-link" href="/register">Lihat semua desain <ArrowRight size={15}/></a></div><div className="template-grid">{templates.map((t) => <article className="template-item" key={t.name}><div className={`template-preview ${t.tone}`}><div className="template-decoration">❧</div><span>{t.style}</span><div className="template-preview-names">{t.initials.split(" & ")[0]} <i>&</i><br/>{t.initials.split(" & ")[1]}</div><small>{t.date}</small><div className="template-seal">r.</div></div><div className="template-meta"><div><h3>{t.name}</h3><p>Undangan digital · Bisa disesuaikan</p></div><span className="template-arrow"><ArrowRight size={17}/></span></div></article>)}</div></section>
    <section id="fitur" className="feature-band"><div className="feature-intro"><div className="eyebrow">LEBIH DARI SEKADAR UNDANGAN</div><h2>Semua yang dibutuhkan,<br/><em>dalam satu cerita.</em></h2><p>Detail kecil membuat hari besar terasa lebih dekat. Kami siapkan ruang untuk semuanya.</p></div><div className="feature-list">{features.map((feature, i) => <div key={feature} className="feature-row"><span className="feature-number">0{i+1}</span><span className="feature-icon">{[<Heart key="h"/>,<Sparkles key="s"/>,<MapPin key="m"/>,<Music2 key="mu"/>,<CalendarDays key="c"/>,<Check key="ch"/>][i]}</span><span>{feature}</span><ArrowRight size={15} className="feature-arrow"/></div>)}</div></section>
    <section id="cara-kerja" className="how-section"><div className="eyebrow">MUDAH DIMULAI, MENYENANGKAN DIJALANI</div><h2>Dari ide kecil menjadi <em>hari tak terlupakan.</em></h2><div className="steps-grid"><div><span>01</span><h3>Pilih desain</h3><p>Temukan tampilan yang paling mencerminkan cerita kalian.</p></div><div><span>02</span><h3>Isi cerita</h3><p>Tambahkan detail pasangan, acara, foto, dan cerita perjalanan.</p></div><div><span>03</span><h3>Bagikan bahagia</h3><p>Preview undangan, lalu bagikan tautan personal ke semua tamu.</p></div></div></section>
    <section id="harga" className="closing-cta"><div className="eyebrow">HARI BESAR DIMULAI DARI SINI</div><h2>Ceritamu layak <em>dirayakan.</em></h2><p>Mulai rancang undangan yang akan selalu ingin kalian buka kembali.</p><Link href="/register" className="button-primary">Mulai buat undangan <ArrowRight size={16}/></Link></section>
    <footer className="site-footer"><Link href="/" className="brand"><span className="brand-mark">r.</span><span>ruang<span className="brand-light">janji</span></span></Link><span>Merayakan awal yang baru, dengan sepenuh hati.</span><span>© 2026 ruangjanji</span></footer>
  </main>;
}
