"use client";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
type InvitationData = { id: string; title?: string; slug: string; status: string; template: string; eventDate?: string | null; quranSurah?: string; quranVerse?: string; quranText?: string; closingText?: string; groom: { name?: string; nickname?: string; fatherName?: string; motherName?: string; birthOrder?: string; instagram?: string; photo?: string; photoPublicId?: string }; bride: { name?: string; nickname?: string; fatherName?: string; motherName?: string; birthOrder?: string; instagram?: string; photo?: string; photoPublicId?: string } };
export function InvitationEditor({ invitation }: { invitation: InvitationData }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const data = new FormData(event.currentTarget); const localDate = String(data.get("eventDate") || ""); const payload = { title: data.get("title"), slug: data.get("slug"), eventDate: localDate ? new Date(localDate).toISOString() : null, quranSurah: data.get("quranSurah"), quranVerse: data.get("quranVerse"), quranText: data.get("quranText"), closingText: data.get("closingText"), template: data.get("template") }; try { const response = await fetch(`/api/invitations/${invitation.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Tidak dapat menyimpan perubahan."); } finally { setBusy(false); } }
  async function setStatus(status: "published" | "draft") { setBusy(true); setError(""); try { const response = await fetch(`/api/invitations/${invitation.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Status gagal diubah."); } finally { setBusy(false); } }
  async function remove() { if (!window.confirm("Hapus draft undangan ini?")) return; setBusy(true); try { const response = await fetch(`/api/invitations/${invitation.id}`, { method: "DELETE" }); if (!response.ok) throw new Error("Undangan gagal dihapus."); router.push("/dashboard/invitations"); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Tidak dapat menghapus undangan."); setBusy(false); } }
  return <><form onSubmit={save} className="mt-7 space-y-7 rounded-xl border border-[#e8e8df] bg-white p-5 md:p-7"><fieldset><legend className="font-serif text-xl">Identitas undangan</legend><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field name="title" label="Nama undangan" value={invitation.title}/><Field name="slug" label="Slug publik" value={invitation.slug}/><p className="text-xs text-stone-500 sm:col-span-2">Tautan undangan: /undangan/{invitation.slug}</p></div></fieldset><fieldset><legend className="font-serif text-xl">Hari & kutipan undangan</legend><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="field-label">Tanggal utama<input className="field-input" name="eventDate" type="datetime-local" defaultValue={toLocalInput(invitation.eventDate)}/></label><Field name="quranSurah" label="Nama surah" value={invitation.quranSurah}/><Field name="quranVerse" label="Ayat" value={invitation.quranVerse}/><label className="field-label sm:col-span-2">Kutipan ayat<textarea className="field-input min-h-28" name="quranText" maxLength={2000} defaultValue={invitation.quranText}/></label><label className="field-label sm:col-span-2">Pesan penutup<textarea className="field-input min-h-24" name="closingText" maxLength={1000} defaultValue={invitation.closingText}/></label></div></fieldset><label className="field-label">Template<select className="field-input" name="template" defaultValue={invitation.template}>{["elegant","romantic","modern","luxury","nusantara"].map((item)=><option key={item} value={item}>{item[0].toUpperCase()+item.slice(1)}</option>)}</select></label>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<button className="button-primary" disabled={busy}>{busy ? "Menyimpan…" : "Simpan perubahan"}</button></form><div className="mt-5 flex flex-wrap gap-3"><button disabled={busy} onClick={()=>setStatus(invitation.status === "published" ? "draft" : "published")} className="button-primary">{invitation.status === "published" ? "Batalkan publikasi" : "Publikasikan undangan"}</button><a className="button-secondary" href={`/undangan/${invitation.slug}${invitation.status === "published" ? "" : "?preview=1"}`} target="_blank" rel="noreferrer">Preview ↗</a><button disabled={busy} onClick={remove} className="button-secondary !border-red-200 !text-red-700">Hapus</button></div></>;
}
function Field({ name, label, value }: { name: string; label: string; value?: string }) { return <label className="field-label">{label}<input className="field-input" name={name} defaultValue={value} maxLength={120}/></label>; }
function toLocalInput(value?: string | null) { if (!value) return ""; const date = new Date(value); const local = new Date(date.getTime() - date.getTimezoneOffset() * 60_000); return local.toISOString().slice(0, 16); }
